Repository googleapis/python-resource-manager, pull requests merged in 2021-08, with the labels that each got.

#99 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: api: cloudresourcemanager, cla: yes, automerge, samples

#100 chore: add missing import in owlbot.py
  owlbot.py
Labels: api: cloudresourcemanager, cla: yes

#96 feat: bump release level to production/stable
  .repo-metadata.json
  README.rst
  docs/README.rst
  setup.py
Labels: api: cloudresourcemanager, cla: yes, automerge

#105 chore: migrate default branch from master to main
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  docs/conf.py
  owlbot.py
Labels: api: cloudresourcemanager, cla: yes
