Repository googleapis/python-resource-manager, pull requests merged in 2021-04, with the labels that each got.

#45 build(python): update docfx job to use new plugin
  noxfile.py
  synth.metadata
Labels: api: cloudresourcemanager, cla: yes, context: full

#46 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: api: cloudresourcemanager, cla: yes

#47 chore: prevent normalization of semver versioning
  setup.py
Labels: api: cloudresourcemanager, automerge, cla: yes

#54 chore(revert): revert preventing normalization
  setup.py
Labels: api: cloudresourcemanager, automerge, cla: yes
